// Generated by Selenium IDE
package test.java;

import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.JavascriptExecutor;


import java.util.*;
public class TestassertionTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    String path = System.setProperty("webdriver.chrome.driver","C:\\drivers\\chromedriver.exe");

    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void testassertion() throws InterruptedException {
    driver.get("http://demo.guru99.com/test/newtours/index.php");
    driver.manage().window().setSize(new Dimension(760, 820));
    driver.findElement(By.linkText("SIGN-ON")).click();
    driver.findElement(By.name("userName")).click();
    driver.findElement(By.name("userName")).sendKeys("m2i");
    driver.findElement(By.name("password")).click();
    driver.findElement(By.name("password")).sendKeys("m2i");
    driver.findElement(By.name("submit")).click();
    Thread.sleep(1000);
    driver.switchTo().frame(1);
    driver.switchTo().defaultContent();
    driver.findElement(By.linkText("Flights")).click();
    {
      List<WebElement> elements = driver.findElements(By.xpath("//td/table/tbody/tr/td[2]/table/tbody/tr/td/img"));
      assert(elements.size() > 0);
    }
  }
}
